// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MetarchyMatch
 * @dev Simple contract to store encrypted phase commits.
 *      The backend acts as a relayer, paying gas so users don't have to.
 */
contract MetarchyMatch {
    address public owner;
    address public relayerAddress;

    // matchId => playerAddress => phaseIndex => commitHash
    mapping(string => mapping(address => mapping(uint8 => bytes32))) public phaseCommits;

    event CommitReceived(string matchId, address player, uint8 phaseIndex, bytes32 commitHash);

    modifier onlyRelayer() {
        require(msg.sender == relayerAddress || msg.sender == owner, "Only relayer can submit");
        _;
    }

    constructor(address _relayerAddress) {
        owner = msg.sender;
        relayerAddress = _relayerAddress;
    }

    /**
     * @dev Allows the relayer to submit a player's commit hash to verify game state in a cheat-proof way.
     * @param matchId A unique id generated by the Node backend.
     * @param player The public address of the player.
     * @param phaseIndex The phase number (e.g. 1 = Distribution, 2 = Bets, 3 = Actions).
     * @param commitHash The KECCAK256 hash of the player's encrypted turn payload.
     */
    function submitCommit(
        string calldata matchId,
        address player,
        uint8 phaseIndex,
        bytes32 commitHash
    ) external onlyRelayer {
        require(phaseCommits[matchId][player][phaseIndex] == bytes32(0), "Phase already committed");
        
        phaseCommits[matchId][player][phaseIndex] = commitHash;
        
        emit CommitReceived(matchId, player, phaseIndex, commitHash);
    }

    function setRelayerAddress(address _newRelayer) external {
        require(msg.sender == owner, "Only owner");
        relayerAddress = _newRelayer;
    }
}
